spring:
  application:
    name: infect-server
  datasource:
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 594741
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    com.infect: debug
  pattern:
    dateformat: HH:mm:ss
mybatis:
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  type-aliases-package: com.infect.entity
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
  mapper-locations: classpath:/mapper/*.xml

infect:
  jwt:
    token-name: Authorization
    railway-employee-secret-key: railway_employee
    railway-employee-ttl: 72000000123
    admin-secret-key: admin
    admin-ttl: 72000000123
    cdc-staff-secret-key: cdc_staff
    cdc-staff-ttl: 72000000123
    medical-staff-secret-key: medical_staff
    medical-staff-ttl: 72000000123
  path:
    diagnosis-file-path: diagnosisReports
    lab-test-file-path: labTestFilePath
    disease-learning-material-path: diseaseLearningMaterialPath

